### DISCUSSION TITLE
New config format question about keybinding layout

### DISCUSSION THREAD

**Discussion by hasezoey** [tramhao/termusic#301] [Q&A] [answered]
I wanted to work on a new config layout to split the server and TUI config settings (so that not too much is loaded) and refactor some property layouts, but have come across a question regarding keybinding config layout:

currently keybindings look like:

```toml
[keys.global_quit.code]
type = "Char"
args = "q"

[keys.global_quit.modifier]
type = "KeyModifiers"
bits = 0
```

but i wanted to make them simpler by only having one entry, but cant decide which modifier layout to go for:

choice 1: one string, delimited with `+` (or some other character like space ` `)
```toml
[keys.global_quit]
key = "q"
modifiers = "SHIFT+CONTROL+ALT"
```

choice 2: a sequence (vec) of strings:
```toml
[keys.global_quit]
key = "q"
modifiers = ["SHIFT", "CONTROL", "ALT"]
```

or any other suggestions?

Note: i plan on treating any extra occurrence as one (like `modifiers = "SHIFT+SHIFT+SHIFT"` the same as `modifiers = "SHIFT"`).

---

EDIT:

choice 3: combined key and modifiers:

```toml
[keys.global_quit]
key = "q+SHIFT+CONTROL+ALT"
```

choice 3.5: basically choice 3, but flatter:
```toml
[keys]
global_quit = "q+SHIFT+CONTROL+ALT"
```
Note: maybe allow both 3 and 3.5 similar to how Cargo.toml's dependencies section works?
