### DISCUSSION TITLE
How to change font color of selected song?

### DISCUSSION THREAD

**Discussion by DaL31** [tramhao/termusic#454] [Q&A] [answered]
Hello,
I want to change the font color since it is currently too dark to read looking like:

![2025-03-1408-27-15](https://github.com/user-attachments/assets/0a2be405-447e-48ca-b18d-f913a527ab09)

I've tried to modify every hexcode and color in the `~/.config/termusic/tui.toml` and in the selected theme.yaml file in `~/.config/termusic/theme` but nothing works after restarting termusic.
So I wanted to ask if that's even possible?

**Comment by tramhao** [comment]
Sure. Please use config editor(`shift+c`) instead. You can select different themes or customize themes. After selecting the theme you want, please use `control+s` to save the configuration.

**Reply by DaL31** [reply]
I've also tried this and changed every color to something obvious  like white, cyan, LightRed but it also didn't work after a restart ('-')?

**Comment by tramhao** [comment]
Did it work before restart? If so, please try to use v0.10.0 which was released last week. It fixed many issues.

**Reply by DaL31** [reply]
Also didn't work after restart.
Always has been like this since last year I started using it. But it's a really minor issue.
I keep my system up to date on a daily basis.

If I have time I will look further into the code to investigate. 
Just wanted to ask first to check if I tried everything correct.

**Comment by tramhao** [comment]
The theme should be applied immediately when you select them in config editor. I checked current master version in both arch linux and windows 11 power shell. Is it because that you're using tmux? It's a known issue that the underlying library of termusic which is tui-realm and tui-rs don't work for tmux or zellij. Thanks.

**Reply by DaL31** [reply]
Neither `tmux` nor `zellij` are installed on my system.
This is what it looks like if I for example the `Termusic Default` theme

![2025-03-1517-10-59](https://github.com/user-attachments/assets/26a3c57e-6fa8-453f-ae82-134131036b19)

or the `Afterglow` theme in config > Themes and Colors

![2025-03-1517-11-36](https://github.com/user-attachments/assets/aac1b493-9a01-4a9c-b68e-59fb233ce812)

Everything but the font color of the current selection changes. Also tried reinstall a couple of times.

**Comment by tramhao** [comment]
would you please post your  tui.toml before and after changing theme? After you select a theme, press enter to preview it, then press ctrl+s to save it.

**Comment by DaL31** [comment]
Sure.

# Before

Current theme is "Afterglow"

## Looks like this

![2025-03-1817-55-24](https://github.com/user-attachments/assets/93934d0c-5fce-4b96-8622-07336c11924b)

## ~/.config/termusic/tui.toml
```toml
version = "2"
com = "same"

[behavior]
quit_server_on_exit = true
confirm_quit = true

[coverart]
align = "bottom right"
size_scale = 0
hidden = false

[style.library]
foreground_color = "White"
background_color = "Reset"
border_color = "Yellow"
highlight_color = "Yellow"
highlight_symbol = "󰶻"

[style.playlist]
foreground_color = "White"
background_color = "Reset"
border_color = "Yellow"
highlight_color = "Yellow"
highlight_symbol = "󰶻"
current_track_symbol = "►"
use_loop_mode_symbol = true

[style.lyric]
foreground_color = "Reset"
background_color = "Reset"
border_color = "Blue"

[style.progress]
foreground_color = "Reset"
background_color = "Reset"
border_color = "Yellow"

[style.important_popup]
foreground_color = "Yellow"
background_color = "Reset"
border_color = "Yellow"

[style.fallback]
foreground_color = "Foreground"
background_color = "Reset"
border_color = "Yellow"
highlight_color = "Yellow"

[theme]
file_name = "Afterglow"
name = "empty name"
author = "empty author"

[theme.primary]
background = "#2c2c2c"
foreground = "#d6d6d6"

[theme.cursor]
text = "#2c2c2c"
cursor = "#d9d9d9"

[theme.normal]
black = "#1c1c1c"
red = "#bc5653"
green = "#909d63"
yellow = "#ebc17a"
blue = "#7eaac7"
magenta = "#aa6292"
cyan = "#86d3ce"
white = "#cacaca"

[theme.bright]
black = "#636363"
red = "#bc5653"
green = "#909d63"
yellow = "#ebc17a"
blue = "#7eaac7"
magenta = "#aa6292"
cyan = "#86d3ce"
white = "#f7f7f7"

[keys]
escape = "escape"
quit = "q"

[keys.view]
view_library = "1"
view_database = "2"
view_podcasts = "3"
open_config = "shift+C"
open_help = "control+h"

[keys.navigation]
up = "k"
down = "j"
left = "h"
right = "l"
goto_top = "g"
goto_bottom = "shift+G"

[keys.global_player]
toggle_pause = "space"
next_track = "n"
previous_track = "shift+N"
volume_up = "+"
volume_down = "-"
seek_forward = "f"
seek_backward = "b"
speed_up = "control+f"
speed_down = "control+b"
toggle_prefetch = "control+g"
save_playlist = "control+s"

[keys.global_lyric]
adjust_offset_forwards = "shift+F"
adjust_offset_backwards = "shift+B"
cycle_frames = "shift+T"

[keys.library]
load_track = "l"
load_dir = "shift+L"
delete = "d"
yank = "y"
paste = "p"
cycle_root = "o"
add_root = "a"
remove_root = "shift+A"
search = "/"
youtube_search = "s"
open_tag_editor = "t"

[keys.playlist]
delete = "d"
delete_all = "shift+D"
shuffle = "r"
cycle_loop_mode = "m"
play_selected = "l"
search = "/"
swap_up = "shift+K"
swap_down = "shift+J"
add_random_songs = "shift+S"
add_random_album = "s"

[keys.database]
add_selected = "l"
add_all = "shift+L"

[keys.podcast]
search = "s"
mark_played = "m"
mark_all_played = "shift+M"
refresh_feed = "r"
refresh_all_feeds = "shift+R"
download_episode = "d"
delete_local_episode = "shift+D"
delete_feed = "x"
delete_all_feeds = "shift+X"

[keys.adjust_cover_art]
move_left = "control+shift+arrowleft"
move_right = "control+shift+arrowright"
move_up = "control+shift+arrowup"
move_down = "control+shift+arrowdown"
increase_size = "control+shift+pageup"
decrease_size = "control+shift+pagedown"
toggle_hide = "control+shift+end"

[keys.config]
save = "control+s"
```

# After

Current theme is "Termusic Default".
- Went to the configs in termusic via `control + c`
- Went to "Theme and Colors"
- selected "Termusic Default" with `return`
- saved theme selection via `control + s`
- selected yes

## Looks like this

![2025-03-1817-57-35](https://github.com/user-attachments/assets/1c051ce2-da65-4d02-8c41-e20158bc7c5e)

## ~/.config/termusic/tui.toml
```toml
version = "2"
com = "same"

[behavior]
quit_server_on_exit = true
confirm_quit = true

[coverart]
align = "bottom right"
size_scale = 0
hidden = false

[style.library]
foreground_color = "White"
background_color = "Reset"
border_color = "Yellow"
highlight_color = "Yellow"
highlight_symbol = "󰶻"

[style.playlist]
foreground_color = "White"
background_color = "Reset"
border_color = "Yellow"
highlight_color = "Yellow"
highlight_symbol = "󰶻"
current_track_symbol = "►"
use_loop_mode_symbol = true

[style.lyric]
foreground_color = "Reset"
background_color = "Reset"
border_color = "Blue"

[style.progress]
foreground_color = "Reset"
background_color = "Reset"
border_color = "Yellow"

[style.important_popup]
foreground_color = "Yellow"
background_color = "Reset"
border_color = "Yellow"

[style.fallback]
foreground_color = "Foreground"
background_color = "Reset"
border_color = "Yellow"
highlight_color = "Yellow"

[theme]
name = "Termusic Default"
author = "Termusic Developers"

[theme.primary]
background = "#101421"
foreground = "#fffbf6"

[theme.cursor]
text = "#1e1e1e"
cursor = "#ffffff"

[theme.normal]
black = "#2e2e2e"
red = "#eb4129"
green = "#abe047"
yellow = "#f6c744"
blue = "#47a0f3"
magenta = "#7b5cb0"
cyan = "#64dbed"
white = "#e5e9f0"

[theme.bright]
black = "#565656"
red = "#ec5357"
green = "#c0e17d"
yellow = "#f9da6a"
blue = "#49a4f8"
magenta = "#a47de9"
cyan = "#99faf2"
white = "#ffffff"

[keys]
escape = "escape"
quit = "q"

[keys.view]
view_library = "1"
view_database = "2"
view_podcasts = "3"
open_config = "shift+C"
open_help = "control+h"

[keys.navigation]
up = "k"
down = "j"
left = "h"
right = "l"
goto_top = "g"
goto_bottom = "shift+G"

[keys.global_player]
toggle_pause = "space"
next_track = "n"
previous_track = "shift+N"
volume_up = "+"
volume_down = "-"
seek_forward = "f"
seek_backward = "b"
speed_up = "control+f"
speed_down = "control+b"
toggle_prefetch = "control+g"
save_playlist = "control+s"

[keys.global_lyric]
adjust_offset_forwards = "shift+F"
adjust_offset_backwards = "shift+B"
cycle_frames = "shift+T"

[keys.library]
load_track = "l"
load_dir = "shift+L"
delete = "d"
yank = "y"
paste = "p"
cycle_root = "o"
add_root = "a"
remove_root = "shift+A"
search = "/"
youtube_search = "s"
open_tag_editor = "t"

[keys.playlist]
delete = "d"
delete_all = "shift+D"
shuffle = "r"
cycle_loop_mode = "m"
play_selected = "l"
search = "/"
swap_up = "shift+K"
swap_down = "shift+J"
add_random_songs = "shift+S"
add_random_album = "s"

[keys.database]
add_selected = "l"
add_all = "shift+L"

[keys.podcast]
search = "s"
mark_played = "m"
mark_all_played = "shift+M"
refresh_feed = "r"
refresh_all_feeds = "shift+R"
download_episode = "d"
delete_local_episode = "shift+D"
delete_feed = "x"
delete_all_feeds = "shift+X"

[keys.adjust_cover_art]
move_left = "control+shift+arrowleft"
move_right = "control+shift+arrowright"
move_up = "control+shift+arrowup"
move_down = "control+shift+arrowdown"
increase_size = "control+shift+pageup"
decrease_size = "control+shift+pagedown"
toggle_hide = "control+shift+end"

[keys.config]
save = "control+s"
```

**Comment by DaL31** [comment, marked as answer]
I just found the reason - my alacritty terminal config.

I've changed
```toml
# ~/.config/alacritty/alacritty.toml
[colors.bright]
black = "#666666"
```
to
```toml
# ~/.config/alacritty/alacritty.toml
[colors.bright]
black = "#ffffff"
```
and the font color changed
![2025-03-1818-13-38](https://github.com/user-attachments/assets/9d83e78c-eb71-4594-a1e8-e4fac87b62e9)

That means the `~/.config/alacritty/alacritty.toml` overwrites the `~/.config/termusic/tui.toml`.
Thank you for your fast responses @tramhao.
