### ISSUE TITLE
Crash: attempt to subtract with overflow; when opening config

### ISSUE THREAD

**Issue by hasezoey** [tramhao/termusic#161]
When i do `SHIFT+C` after first having saved the config, the TUI panics. removing that line fixes the issue.

https://github.com/tramhao/termusic/blob/57429abab36ee5ffc77308a4466a554c6fb177fb/tui/src/ui/components/config_editor/general.rs#L50

Error:

```txt
thread 'main' panicked at tui/src/ui/components/config_editor/general.rs:50:38:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

note that this might not be the complete backtrace because it was thrown while still in the alternate screen and so was messed up

this only started happening after i first saved the config once, which resulted in the following lines (truncated):

```toml
music_dir = []
player_port = 50101
player_loop_mode = "Random"
player_volume = 15
player_speed = 10
player_gapless = true
podcast_simultanious_download = 3
podcast_max_retries = 3
podcast_dir = "/home/hasezoey/Music/podcast"
player_seek_step = "Auto"
player_remember_last_played_position = "Auto"
enable_exit_confirmation = false
playlist_display_symbol = false
playlist_select_random_track_quantity = 20
playlist_select_random_album_quantity = 5
theme_selected = "default"
kill_daemon_when_quit = true
player_use_mpris = true
player_use_discord = false
```
