### ISSUE TITLE
termusic fails on start

### ISSUE THREAD

**Issue by i-am-logger** [tramhao/termusic#367]
![image](https://github.com/user-attachments/assets/bdf1148c-7d40-4a2c-93d4-081ddbdfbf96)

OS: NixOS 24.11.20240904.ad416d0 (Vicuna) x86_64
Kernel: Linux 6.10.7

**Comment by tramhao** [comment]
Would you please run termusic-server first and see if it can be started? If not, please check the IP address in configuration file, and set it as 127.0.0.1

**Comment by i-am-logger** [comment]
![image](https://github.com/user-attachments/assets/7de20e4c-23cf-432d-b76f-9f5343c1c89f)

whart should be in the config file? its not being created

**Comment by tramhao** [comment]
Please check this issue. https://github.com/tramhao/termusic/issues/356
Basically you can change the configuration and it'll work.

**Comment by i-am-logger** [comment]
yes, already looked. i'm looking for the default file configuration as i'm not sure what it looks like

**Comment by tramhao** [comment]
Currently the default file configuration is `::1` . It works for me both `::` and `::1` under windows.

**Comment by tramhao** [comment]
I don't have experience with NixOS. Under arch, the configuration file is in $HOME/.config/termusic/server.toml

**Comment by i-am-logger** [comment]
this file doesn't exist

**Comment by i-am-logger** [comment]
this made it work

server.toml
```toml
version = "2"

[com]
port = 23000
address = "127.0.0.1"

[player]
music_dirs = ["~/Music"]
library_scan_depth = 10
loop_mode = "playlist"
volume = 30
speed = 10
gapless = true
use_mediacontrols = true
set_discord_status = true
random_track_quantity = 20
random_album_min_quantity = 5

[player.remember_position]
music = "no"
podcast = "yes"

[player.seek_step]
short_tracks = 5
long_tracks = 30

[podcast]
concurrent_downloads_max = 3
max_download_retries = 3
download_dir = "~/Music/podcast"
```
