### ISSUE TITLE
Cannot save/load music paths

### ISSUE THREAD

**Issue by Else00** [tramhao/termusic#508]
## Environment & Versions

- System: macOS 15.5 24F74
- Termusic version: `0.10.0`
- Rust version: 1.87.0 (17067e9ac 2025-05-09) (Homebrew)

Logs:
Not available due to issues with logging functionality described below.

## Description of the Problem

I'm encountering several issues related to setting the music directory, especially with paths containing spaces, and with the logging functionality.

### Issue 1: Music directory path with spaces not saving via TUI settings

When I try to add the following path to the "Root Music Directory" in the TUI settings (Shift+C), it does not save:
Path: `/Volumes/UNNAS/OLD HDD 6TB/musica/Plex Music`

I have also tried escaping the spaces: `/Volumes/UNNAS/OLD\ HDD\ 6TB/musica/Plex\ Music`

**Steps to reproduce:**
1. Open Termusic.
2. Press `Shift+c` to go to settings.
3. Navigate to "Root Music Directory".
4. Enter the path `/Volumes/UNNAS/OLD HDD 6TB/musica/Plex Music`.
5. Press `Ctrl+s` to save.
6. Re-enter settings (`Shift+c`).

**Expected behavior:**
The path should be saved and displayed in the "Root Music Directory" field.

**Actual behavior:**
The path is gone, and the field is empty or reset to its previous value.

### Issue 2: Termusic fails to start when music directory with spaces is manually added to `server.toml`

If I manually edit `~/Library/Application Support/termusic/server.toml` to include the path, Termusic fails to start properly.

**`server.toml` configuration:**
```toml
version = "2"

[com]
port = 50101
address = "::"

[player]
music_dirs = ["/Volumes/UNNAS/OLD HDD 6TB/musica/Plex Music"]
library_scan_depth = 10
loop_mode = "playlist"
volume = 100
speed = 10
gapless = true
use_mediacontrols = true
set_discord_status = false
random_track_quantity = 20
random_album_min_quantity = 5

[player.remember_position]
music = "no"
podcast = "yes"

[player.seek_step]
short_tracks = 5
long_tracks = 30

[podcast]
concurrent_downloads_max = 3
max_download_retries = 3
download_dir = "/Users/else/Music/podcast"
```

**Terminal output and behavior:**
When starting `termusic` with the above configuration:
```shell
❯ termusic
Logging to file "/var/folders/vz/wd0r1m8x31z1sp5z_k_wjn800000gn/T/termusic-tui.log"
Server process ID: 47308
^C
```
Termusic prints the "Server process ID" and then hangs. No TUI appears, and I have to manually stop it with `Ctrl+C`.

Subsequently, trying to `cat` the default log file shows it wasn't created or written to:
```shell
❯ cat "/var/folders/vz/wd0r1m8x31z1sp5z_k_wjn800000gn/T/termusic-tui.log"
[bat error]: '/var/folders/vz/wd0r1m8x31z1sp5z_k_wjn800000gn/T/termusic-tui.log': No such file or directory (os error 2)
```
(Note: The `[bat error]` is from the `cat` command itself, indicating the log file was not found).

### Issue 3: Termusic panics when `--log-file` argument is used

When I try to specify a log file using the `--log-file` argument, `termusic` panics, even if the file exists.

**Steps to reproduce:**
1. Create an empty file: `touch file.log`
2. Run termusic with the log file argument: `termusic --log-file file.log`

**Terminal output (panic):**
```shell
❯ touch file.log
❯ termusic --log-file file.log

thread 'main' panicked at /Users/else/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/termusic-0.10.0/src/logger.rs:41:14:
Expected flexi_logger to be able to start: OutputIo(Os { code: 2, kind: NotFound, message: "No such file or directory" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This occurs even though `file.log` was created in the current directory. The help output for `--log-file` is:
```
      --log-file <LOG_FILE>          Set logging file [env: TM_LOGFILE=] [default: /var/folders/vz/wd0r1m8x31z1sp5z_k_wjn800000gn/T/termusic-tui.log]
```

These issues make it difficult to configure `termusic` for music libraries on certain paths and to debug problems using custom log files.
